[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisor.pid

# https://askubuntu.com/a/932612
[supervisorctl]

[program:frankenphp]
command=php bin/console frankenphp:run
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:worker]
command=/app/worker
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:messenger-worker-async]
command=php bin/console messenger:consume async --time-limit=1800 --memory-limit=256M
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:messenger-worker-scheduler-default]
command=php bin/console messenger:consume scheduler_default --time-limit=1800 --memory-limit=256M
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:messenger-worker-scheduler-server]
command=php bin/console messenger:consume scheduler_server --time-limit=1800 --memory-limit=256M
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
